---
  - name: Ansible copy directory to the remote server
    copy:
      src: ./files/
      dest: /pihole
      
  - name: Start Docker containers using Docker-Compose
    command: docker-compose  -f /pihole/docker-compose.yml up -d
    register: output

  - name: Watch docker-compose output
    debug:
      var: output

  - name: Start Tailescale
    command: docker exec tailscaled tailscale up --authkey=$TS_AUTH_KEY --accept-dns=false --advertise-routes=10.2.0.0/24
    
  - name: Add list to pihole
    command: docker exec pihole echo 'https://dbl.oisd.nl' >> /etc/pihole/adlists.list
